### ISSUE TITLE
MongoDB Atlas

### ISSUE THREAD

**Issue by shreyashrangrej** [badrinathpathak/CRUD-API-Node.js-Express-and-MongoDB#1]
Hay Badrinath can i use mongodb atlas instance for this API?

**Comment by badrinathpathak** [comment]
@shreyashrangrej Yes, you can use MongoDB atlas instance. Configure the same in the config directory.

**Comment by shreyashrangrej** [comment]
Indeed, I was able to able to connect this backend with my SAPUI5 front-end application, your API worked like a charm with my frontend
